version: "3.8"
services:
  trello:
    tty: true
    stdin_open: true
    container_name: trello
    build:
      context: ./client/
    ports:
      - 4000:3000
    volumes:
      - ./client/:/app
      - /app/node_modules
